# Generated by Django 5.2.7 on 2025-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_contacto_delete_producto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacto",
            name="telefono",
            field=models.CharField(max_length=11),
        ),
    ]
